SELECT n.CRCNO
	 , m.BRNO
     , m.BRNAME
	 , a.SERNO 
	 , isnull(b.ACCOUNTNAME, c.ACCOUNTNAME) AS ACCOUNTNAME
	 , isnull(d.COLDESC, e.COLDESC) AS CUSTTYPE
	 , isnull(b.GROUPNAME, c.GROUPNAME) AS GROUPNAME
	 , h.NAME as MGRNAME
	 , i.NAME as EDITNAME
	 , a.VISITDATE
	 , a.RECORDDATE
	 , a.DIARYNO
	 , isnull(l.OPPNUM,0) as OPPNUM
	 , k.ENDPROJECT
FROM
	[iom].[dbo].[CUSTMGR_DIARY] a LEFT OUTER JOIN [iom].[dbo].CUSTMGR_CUSTLIST b ON a.BRNO = b.BRNO AND a.SERNO = b.SERNO
	LEFT OUTER JOIN [iom].[dbo].CUSTMGR_CUSTLIST_PASS c
		ON a.BRNO = c.BRNO AND a.SERNO = c.SERNO
	LEFT OUTER JOIN [iom].[dbo].CUSTMGR_OPTION d
		ON b.CUSTTYPE = d.COLVALUE 
	LEFT OUTER JOIN [iom].[dbo].CUSTMGR_OPTION e
		ON c.CUSTTYPE = e.COLVALUE 
	LEFT OUTER JOIN [iom].[dbo].CUSTMGR_GROUP f
		ON b.ENTSERNOMAIN = f.ENTSERNOMAIN
	LEFT OUTER JOIN [iom].[dbo].CUSTMGR_GROUP g
		ON c.ENTSERNOMAIN = g.ENTSERNOMAIN
	LEFT OUTER JOIN chb_pub.dbo.EMPLOYEE h
		ON a.MGREMPNO = h.STAFF
	LEFT OUTER JOIN chb_pub.dbo.EMPLOYEE i
		ON a.EDITEMPNO = i.STAFF
	LEFT OUTER JOIN (SELECT DIARYNO,count(1)as OPPNUM FROM [iom].[dbo].CUSTMGR_DIARYOPPORTUNITIES GROUP BY DIARYNO) l on a.DIARYNO = l.DIARYNO				
	LEFT OUTER JOIN [iom].[dbo].CUSTMGR_DIARYOPPMAPPING j ON a.DIARYNO = j.DIARYNO	
	LEFT OUTER JOIN [iom].[dbo].CUSTMGR_OPPORTUNITIES k
		ON j.OPPNO = k.OPPNO and k.OPPTYPE = (SELECT max(OPPTYPE)
											  FROM
												  [iom].[dbo].CUSTMGR_OPPORTUNITIES
											  WHERE
												  CUSTMGR_OPPORTUNITIES.OPPNO = k.OPPNO
											  GROUP BY OPPNO)
    LEFT OUTER JOIN chb_pub.dbo.BRANCH m
		ON a.BRNO = m.BRNO
	LEFT OUTER JOIN chb_pub.dbo.crc_rel_br n
		ON a.BRNO = n.BRNO  												  		
WHERE  1=1 AND a.BRNO in ( SELECT BRNO FROM chb_pub.dbo.crc_rel_br	WHERE CRCNO ='3027')
